---
# tasks file for student.bash_env
- name: put away .bashrc
  ansible.builtin.template:
    src: templates/bashrc.j2
    dest: /etc/skel/.bashrc
    owner: root
    group: root
    mode: '0644'

- name: put away .bash_profile
  ansible.builtin.copy:
    src: files/bash_profile
    dest: /etc/skel/.bash_profile
    owner: root
    group: root
    mode: '0644'

- name: put away .vimrc
  ansible.builtin.copy:
    src: files/vimrc
    dest: /etc/skel/.vimrc
    owner: root
    group: root
    mode: '0644'
