---
# tasks file for student.bash_env
- name: put away .bashrc
  block:
    - name: prompt_color blue
      ansible.builtin.template:
        src: templates/bashrc_blue.j2
        dest: /etc/skel/.bashrc
        owner: root
        group: root
        mode: '0644'
  rescue:
    - name: prompt_color other
      ansible.builtin.template:
        src: templates/bashrc.j2
        dest: /etc/skel/.bashrc
        owner: root
        group: root
        mode: '0644'
  when: prompt_color == 'blue'

- name: put away .bash_profile
  ansible.builtin.copy:
    src: files/bash_profile
    dest: /etc/skel/.bash_profile
    owner: root
    group: root
    mode: '0644'

- name: put away .vimrc
  ansible.builtin.copy:
    src: files/vimrc
    dest: /etc/skel/.vimrc
    owner: root
    group: root
    mode: '0644'
